name: paclage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Building package
        run: |
          echo "Node version"
          node -v
          echo "Yarn version"
          yarn -v
          yarn install
          yarn run publish

      - name: Uploading in Github artifactory
        uses: actions/upload-artifact@v2
        with:
          name: wf-support-builder
          path: publish
