name: package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Building package
        run: |
          set -e
          echo "Node version: $(node -v)"
          echo "Yarn version: $(yarn -v)"
          echo "Node version"
          yarn install
          yarn run publish
          ls -la publish

      - name: Uploading in Github artifactory
        uses: actions/upload-artifact@v4
        with:
          name: wf-support-builder
          path: publish
